Proyecto_Final/Models/Gallina.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Proyecto_Final.Models
{
    public class Gallina
    {
        public int IdGallina { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public int IdRaza { get; set; }
        public string Raza { get; set; }
        public int IdUsuario { get; set; }
        public DateTime Fecha_Alta { get; set; }
        public string Fecha { get; set; }
        public string Dimensiones { get; set; }
        [Required]
        public string Sexo { get; set; }
        public string Descripcion { get; set; }
        [Required]
        public string Localidad { get; set; }
        public string[] Tags { get; set; }
        [Required]
        public double Precio { get; set; }
        public double Peso { get; set; }
        public int ValorHuevos { get; set; }
        public string Audio { get; set; }
        public int Views { get; set; }
        public bool Venta { get; set; }
        public string Foto { get; set; }
        public string[] Fotos { get; set; }
        public int HuevosGallina { get; set; }
        public string AudioGallo { get; set; }
        public bool Ventas { get; set; }

        public string FotoUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Favorito { get; set; }

       

        public string NomUsuario { get; set; }
        public string FotUsuario { get; set; }

    }
}

Proyecto_Final/Controllers/GallinaController.cs
using MySql.Data.MySqlClient;
using Proyecto_Final.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_Final.Controllers
{
    public class GallinaController: BaseController
    {

        public ActionResult Commit()
        {
            return View();
        }

        public GallinaController() : base()
        {
           this._model = new Gallina();
           this._table = "gallina";
        }//OK

        public List<Object> ObtenerGallinasFavoritas(int idUsuario)
        {
            if (_conn.State == System.Data.ConnectionState.Closed)
            {
                _conn.Open();
            }
            try
            {
                string sql = "SELECT g.*, r.raza, u.nombre nombreUsuario, u.foto fotoUsuario, p.Provincia";
                sql += " FROM favorito f";
                sql += " left join gallina g on f.idGallina=g.idGallina";
                sql += " left join raza r on g.idRaza=r.idRaza";
                sql += " left join usuario u on u.idUsuario=g.idUsuario";
                sql += " left join provincias p on p.idProvincias=u.idProvincias";
                sql += " where g.ventas=0 and f.idUsuario=" + idUsuario + ";";
                MySqlCommand cmd = new MySqlCommand(sql, _conn);
                MySqlDataReader rdr = cmd.ExecuteReader();
                List<Object> resultado = new List<object>();
                while (rdr.Read())
                {
                    resultado.Add(this.ToModelGallinaHome(rdr));
                }
                rdr.Close();
                _conn.Close();
                return resultado;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                _conn.Close();
                return null;
            }
        }

        private List<Gallina> ConsultarFavorito(List<Gallina> gallinas, int loggedid)
        {
            if (loggedid==0)
            {
                
            }
            else { FavoritoController favoritoController = new FavoritoController();
                foreach (Gallina gallina in gallinas)
                {
                    if (favoritoController.ConsultarFavorito(loggedid, gallina.IdGallina))
                    {
                        gallina.Favorito = "/images/icons8-heart-red-32.png";
                    }
                    else
                    {
                        gallina.Favorito = "/images/icons8-heart-outline-32.png";
                    }
                }}
            return gallinas;
        }

        public List<Gallina> ObtenerGallinas(int loggedid, int idUsuario)
        {
            string sql = "SELECT g.*, r.raza, u.nombre nombreUsuario, u.foto fotoUsuario, p.Provincia";
            sql += " FROM gallina g";
            sql += " left join raza r on g.idRaza=r.idRaza";
            sql += " left join usuario u on u.idUsuario = g.idUsuario";
            sql += " left join provincias p on p.idProvincias = u.idProvincias";
            sql += " where g.idUsuario='" + idUsuario + "' and g.ventas=0;";
            List<Object> gallinasObj = this.getAllGallinaHome(sql);
            List<Gallina> gallinas = this.ConvertList<Gallina>(gallinasObj);
            return this.ConsultarFavorito(gallinas, loggedid);
        }

        public List<Gallina> ObtenerGallinas(int loggedid)
        {
            string sql = "SELECT g.*, r.raza, u.nombre nombreUsuario, u.foto fotoUsuario, p.Provincia";
            sql += " FROM gallina g";
            sql += " left join raza r on g.idRaza=r.idRaza";
            sql += " left join usuario u on u.idUsuario = g.idUsuario";
            sql += " left join provincias p on p.idProvincias = u.idProvincias";
            sql += " where g.ventas=0;";
            List<Object> gallinasObj = this.getAllGallinaHome(sql);
            List<Gallina> gallinas = this.ConvertList<Gallina>(gallinasObj);
            return this.ConsultarFavorito(gallinas, loggedid);
        }

        public List<Object> getAllGallinaHome(string query = null)
        {
            if (_conn.State == System.Data.ConnectionState.Closed)
            {
                _conn.Open();
            }
            try
            {
                string sql = (query == null) ? string.Format("SELECT * FROM {0} limit 100", _table) : query;
                MySqlCommand cmd = new MySqlCommand(sql, _conn);
                MySqlDataReader rdr = cmd.ExecuteReader();
                List<Object> resultado = new List<Object>();
                while (rdr.Read())
                {
                    resultado.Add(ToModelGallinaHome(rdr));
                }
                _conn.Close();
                return resultado;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                _conn.Close();
                return null;
            }
        }

        public Object ToModelGallinaHome(MySqlDataReader rdr)
        {
            Gallina gallina = new Gallina();
            gallina.IdGallina = Convert.ToInt32(rdr["idgallina"]);
            gallina.IdRaza = Convert.ToInt32(rdr["idRaza"]);
            gallina.Raza = rdr["Raza"].ToString();
            gallina.Nombre = rdr["nombre"].ToString();
            gallina.Dimensiones = rdr["Dimensiones"].ToString();
            gallina.Peso = Convert.ToDouble(rdr["peso"]);
            gallina.Sexo = rdr["sexo"].ToString();
            gallina.Precio = Convert.ToDouble(rdr["precio"]);
            gallina.Views = Convert.ToInt32(rdr["views"]);
            gallina.Fecha_Alta = Convert.ToDateTime(rdr["fechaAlta"]);
            gallina.HuevosGallina = Convert.ToInt32(rdr["huevosGallina"]);
            gallina.AudioGallo = rdr["audioGallo"].ToString();
            gallina.IdUsuario = Convert.ToInt32(rdr["idUsuario"]);
            gallina.NombreUsuario = rdr["nombreUsuario"].ToString();
            gallina.Ventas = Convert.ToBoolean(rdr["ventas"]);

            gallina.Fotos = AllFotos(gallina.IdGallina);
            gallina.Foto = gallina.Fotos[0];

            gallina.Localidad = rdr["Provincia"].ToString();
            gallina.FotoUsuario = rdr["fotoUsuario"].ToString();
            

            return gallina;
        }

        public override Object ToModel(MySqlDataReader rdr)
        {
            Gallina gallina = new Gallina();
            gallina.IdGallina = Convert.ToInt32(rdr["idGallina"]);
            gallina.IdRaza = Convert.ToInt32(rdr["idRaza"]);
            gallina.Raza = rdr["Raza"].ToString();
            gallina.Nombre = rdr["nombre"].ToString();
            gallina.Dimensiones = rdr["Dimensiones"].ToString();
            gallina.Peso = Convert.ToDouble(rdr["peso"].ToString());//Convierto primero a string lo devuelto por la base de datos para que c# pueda convertirlo bien a double
            gallina.Sexo = rdr["sexo"].ToString();
            gallina.Precio = Convert.ToDouble(rdr["precio"]);
            gallina.Views = Convert.ToInt32(rdr["views"]);
            gallina.Fecha_Alta = Convert.ToDateTime(rdr["fechaAlta"]);
            gallina.HuevosGallina = Convert.ToInt32(rdr["huevosGallina"]);
            gallina.AudioGallo = rdr["audioGallo"].ToString();
            gallina.IdUsuario = Convert.ToInt32(rdr["idUsuario"]);
            gallina.NombreUsuario = rdr["nombreUsuario"].ToString();
            gallina.Ventas = Convert.ToBoolean(rdr["ventas"]);

            gallina.Fotos = AllFotos(gallina.IdGallina);
            gallina.Foto = gallina.Fotos[0];
            gallina.Descripcion = rdr["descripcion"].ToString();

            gallina.Views = Convert.ToInt32(rdr["views"]);
            gallina.Localidad = rdr["localidad"].ToString();
            gallina.ValorHuevos = Convert.ToInt32(rdr["huevosGallina"]);
            gallina.Audio = rdr["audioGallo"].ToString();
            gallina.Raza = this.NombreRaza(gallina.IdRaza);
            gallina.Tags = this.UpdateTags(gallina.IdGallina);
            
            string[] usuario = new string[2];
            usuario = this.AllUsuario(gallina.IdGallina);
            gallina.NomUsuario = usuario[0];
            gallina.FotUsuario = usuario[1];

            gallina.Fecha = String.Format(gallina.Fecha_Alta.Day.ToString()+"/"+ gallina.Fecha_Alta.Month.ToString() + "/" + gallina.Fecha_Alta.Year.ToString() );

            gallina.FotoUsuario = rdr["fotoUsuario"].ToString();
            

            return gallina; 
        }//OK

        public  Gallina TooModel(MySqlDataReader rdr)
        {
            Gallina gallina = new Gallina();
            gallina.IdGallina = Convert.ToInt32(rdr["idGallina"]);
            gallina.IdRaza = Convert.ToInt32(rdr["idRaza"]);
            gallina.Nombre = rdr["nombre"].ToString();
            gallina.Dimensiones = String.Format(rdr["dimensiones"].ToString()+" cm");
            gallina.Precio = Convert.ToDouble(rdr["precio"].ToString());
            gallina.Peso = Convert.ToDouble(rdr["peso"].ToString());
            gallina.IdUsuario = Convert.ToInt32(rdr["idUsuario"]);
            gallina.Fecha_Alta = Convert.ToDateTime(rdr["fechaAlta"]);
            gallina.Descripcion = rdr["descripcion"].ToString();
            gallina.Fotos = this.AllFotos(gallina.IdGallina);
            gallina.Foto = gallina.Fotos[0];
            gallina.Views = Convert.ToInt32(rdr["views"]);
            gallina.Localidad = rdr["localidad"].ToString();
            gallina.ValorHuevos = Convert.ToInt32(rdr["huevosGallina"]);
            gallina.Audio = rdr["audioGallo"].ToString();
            gallina.Raza = this.NombreRaza(gallina.IdRaza);
            gallina.Tags = this.UpdateTags(gallina.IdGallina);
            gallina.Sexo = rdr["sexo"].ToString();

            string[] usuario = new string[2];
            usuario = this.AllUsuario(gallina.IdGallina);
            gallina.NomUsuario = usuario[0];
            gallina.FotUsuario = usuario[1];

Proyecto_Final/Views/Gallina/Borrar.cshtml
@model Proyecto_Final.Models.Gallina

@{
    ViewBag.Title = "Borrar";
}



    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()


            <div class="row" style="margin-top:60px;">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-2 "></div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 ">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 enunciado-Dm">Deseas borrarme ??</div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 borrar-gallina-dm"></div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="form-actions no-color text-center">
                                <input type="submit" value="Borrar" class="btn btn-warning borrar-gallina-dm" />                              
                            </div>
                        </div>
                    </div>
                </div>
               
            </div>
        
    }

Proyecto_Final/Views/Gallina/Commit.cshtml
@model Proyecto_Final.Models.Gallina

@{
    ViewBag.Title = "Commit";
}



<div class="row" style="margin-top:60px;">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-2 "></div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 ">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 enunciado-Dm">Y voló!!</div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 commit-dm"></div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="text-center" style="margin-top:20px;" >
                    <img class="inicio" src="~/Images/flecha-izquierda.png"/> 
                    <a href="/" id="volver" class="btn inicio"></a>
                </div>
            </div>
        </div>
    </div>

</div>

Proyecto_Final/Views/Gallina/Create.cshtml
@model Proyecto_Final.Models.Gallina

@{
    ViewBag.Title = "Create";
    List<SelectListItem> listadoRazas = (List<SelectListItem>)ViewBag.Razas;
    List<SelectListItem> listadoLocalidad = (List<SelectListItem>)ViewBag.Localidad;
}



@using (Html.BeginForm("Create", "Gallina", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div style="margin-top:30px;"></div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-lg-3 col-md-1 col-sm-1 col-xs-2 "></div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 enunciado-Dm ">
            <p>Sube tu gallina :</p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-1 col-sm-1 col-xs-3 "></div>
        <div class="col-lg-6 col-md-10 col-sm-10 col-xs-6 ">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 foto-vacia-Dm">
					<label for="customFile2" class="subir-foto-Dm"></label>
					<input type="file" name="file" class="custom-file-input" id="customFile2" style="display: none;">
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 foto-vacia-Dm">
					<label for="customFile2" class="subir-foto-Dm"></label>
					<input type="file" name="file1" class="custom-file-input" id="customFile2" style="display: none;">
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 foto-vacia-Dm">
					<label for="customFile3" class="subir-foto-Dm"></label>
					<input type="file" name="file2" class="custom-file-input" id="customFile3" style="display: none;">
				</div>

				<div class="row">

					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 formulario-Dm">
						<div class="form-group">
							<label for="exampleFormControlInput1">Nombre</label>

							@Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nombre" } })
							@Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12  formulario-Dm">
						<div class="form-group ">
							<label for="exampleFormControlInput1">Precio</label>
							@Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control precio-Dm", @placeholder = "€" } })

						</div>
					</div>

				</div>
				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 formulario-Dm">
						<label for="exampleFormControlSelect1">Raza</label>

						@Html.DropDownListFor(model => model.IdRaza, listadoRazas, htmlAttributes: new { @class = "form-control " })
						@Html.ValidationMessageFor(model => model.Raza, "", new { @class = "text-danger" })

					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12  formulario-Dm" style="margin-top:30px;">
						<input type="hidden" name="sexo" id="sexo_ave" />
						<button class="btn hombre-Dm" title="Gallo" value="Macho" type="button" onclick="Macho()"></button>
						<button class="btn mujer-Dm" title="Gallina" value="Hembra" type="button" onclick="Hembra()"></button>

					</div>

				</div>
				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 formulario-Dm">
						<div class="form-group">
							<label for="exampleFormControlInput1">Localidad</label>
							@Html.DropDownListFor(model => model.Localidad, listadoLocalidad, htmlAttributes: new { @class = "form-control " })
							@Html.ValidationMessageFor(model => model.Localidad, "", new { @class = "text-danger" })
						</div>
					</div>
					<div id="num_huevos" class="col-lg-6 col-md-6 col-sm-8 col-xs-12  formulario-Dm" style="margin-top:30px; display:none;">
						<input type="hidden" name="valorHuevos" id="valor_huevo" value="0" />
						<button class="btn huevo-Dm" title="0 Huevos/Semana" id="huevo1" type="button" onclick="cant_huevos(1)"></button>
						<button class="btn huevo-Dm" title="1-2 Huevos/Semana" id="huevo2" type="button" onclick="cant_huevos(2)"></button>
						<button class="btn huevo-Dm" title="2-3 Huevos/Semana" id="huevo3" type="button" onclick="cant_huevos(3)"></button>
						<button class="btn huevo-Dm" title="4-5 Huevos/Semana" id="huevo4" type="button" onclick="cant_huevos(4)"></button>
						<button class="btn huevo-Dm" title="+5 Huevos/Semana" id="huevo5" type="button" onclick="cant_huevos(5)"></button>
					</div>
					<div id="sonido_gallo" class="col-lg-6 col-md-6 col-sm-6 col-xs-12  formulario-Dm" style="margin-top:30px; display:none;">
						<div style="display:inline-block">
							<label class="gallo-simbolo-Dm"></label>
							<label for="customFile4" class="altavoz-Dm" title="Como canta tu gallo?"></label>
							<input type="file" name="sonido" class="custom-file-input" id="customFile4" style="display: none;">
						</div>
					</div>

				</div>
				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 formulario-Dm">
						<div class="form-group">
							<label for="exampleFormControlInput1">Dimensiones</label>
							@Html.EditorFor(model => model.Dimensiones, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nombre" } })

						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12  formulario-Dm">
						<div class="form-group ">
							<label for="exampleFormControlInput1">Peso</label>
							@Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control precio-Dm", @placeholder = "Kgs" } })

						</div>
					</div>

				</div>
				<div class="row  formulario-Dm descripcion-Dm">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">Tags</div>
					<div class="col-lg-4 col-md-4 col-sm- col-xs-12 ">
						<input type="text" class="form-control tag" name="tag1" placeholder="Tag">
					</div>
					<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 ">
						<input type="text" class="form-control tag " name="tag2" placeholder="Tag">
					</div>
					<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 ">
						<input type="text" class="form-control tag" name="tag3" placeholder="Tag">
					</div>
				</div>

				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 formulario-Dm">
						<div class="form-group">
							<label for="exampleFormControlTextarea1">Descripción</label>
							<textarea class="form-control"
									  id="exampleFormControlTextarea1"
									  rows="3"
									  cols="20"
									  name="descripcion"
									  style="max-width:800px;"
									  placeholder="Mi Ramona es la más bonita..."></textarea>

						</div>
					</div>

				</div>

				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-8 col-xs-8  form-group formulario-Dm">
						<button type="submit" class="btn subir-Dm">Subir</button>
					</div>
				</div>
			</div>
        </div>

		
    </div>

    <script>
        function Macho() {

            document.getElementById('sonido_gallo').style.display = 'block';
            document.getElementById('num_huevos').style.display = 'none';
            $('#sexo_ave').val('Macho');

        }
        function Hembra() {


            document.getElementById('sonido_gallo').style.display = 'none';
            document.getElementById('num_huevos').style.display = 'block';
            $('#sexo_ave').val('Hembra');

        }
        function cant_huevos(elhuevo) {
            $('#valor_huevo').val(elhuevo);
            console.log('aSDASD');

		}
		


    </script>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval");
}