Proyecto_Final/Models/Home.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyecto_Final.Models
{
    public class Home
    {
        public List<Gallina> Gallinas { get; set; }
        public List<Raza> Razas { get; set; }
        public List<Provincia> Provincias { get; set; }
        public List<Blog> Blogs { get; set; } 
    }
}

Proyecto_Final/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_Final.Models;
using MySql.Data.MySqlClient;

namespace Proyecto_Final.Controllers
{
    public class BlogController : BaseController
    {
        private static int contadorViews = 0;

        public BlogController() : base()
        {
            this._model = new Blog();
            this._table = "blog";
            
        }

        // GET: Blog
        public ActionResult Index()
        {
            /*cambiar listado de objectos para listado del blog en this.getall */
            List<Object> obj = this.getAll();
            //ViewData["Index"] =  ;
            return View(this.ConvertList<Blog>(obj));
        }
        public ActionResult Lista()
        {
            List<Object> obj = this.getAll();
            return View(this.ConvertList<Blog>(obj));
        }

        public ActionResult Blog(int idBlog)
        {
            ++contadorViews;
            Infoblog info = new Infoblog();
            info.Blog = (Blog) getBlogbyId(idBlog);
            info.Blog.Views = contadorViews;
            info.Comentarios = ObtenerListadoComentarios(idBlog);
            return View(info);
        }

        private List<ComentarioBlog> ObtenerListadoComentarios(int idUsuario)
        {
            ComentarioBlogController comentarioblogcontroller = new ComentarioBlogController(); 
            List<Object> comentariosObj = comentarioblogcontroller.ObtenerComentarios(idUsuario);
            return comentarioblogcontroller.ConvertList<ComentarioBlog>(comentariosObj);
        }
        

        public override Object ToModel(MySqlDataReader rdr)
        {
            Blog Blog = new Blog();
            Blog.IdBlog = Convert.ToInt32(rdr["idBlog"]);
            Blog.IdUsuario = Convert.ToInt32(rdr["idUsuario"]);
            Blog.Titulo = rdr["titulo"].ToString();
            Blog.Texto = rdr["texto"].ToString();
            Blog.Resumen = rdr["resumen"].ToString();
            Blog.Fecha = Convert.ToDateTime(rdr["fecha"]);
            Blog.Foto = rdr["foto"].ToString();
            Blog.Like =Convert.ToInt32(rdr["like"]);          
            Blog.DisLike = Convert.ToInt32(rdr["dislike"]);         
            Blog.Views = Convert.ToInt32(rdr["views"]);
            return Blog; 
        }

        public Object getBlogbyId(int id)
        {
            if (_conn.State == System.Data.ConnectionState.Closed)
            {
                _conn.Open();
            }
            try
            {
                string sql = string.Format("SELECT * FROM {0} WHERE IdBlog={1}", _table, id);
                MySqlCommand cmd = new MySqlCommand(sql, _conn);
                MySqlDataReader rdr = cmd.ExecuteReader();
                rdr.Read();
                Object ob = ToModel(rdr);
                rdr.Close();
                _conn.Close();
                return ob;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                _conn.Close();
                return null;
            }
        }

    }
}

Proyecto_Final/Controllers/HomeController.cs
using Proyecto_Final.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_Final.Controllers
{
    public class HomeController : Controller
    {
        private List<Gallina> ObtenerListadoGallinas(int loggedid)
        {
            GallinaController gallinaController = new GallinaController();
            return gallinaController.ObtenerGallinas(loggedid);
        }

        private List<Raza> ObtenerRazasGallinas()
        {
            RazaController razaController = new RazaController();
            List<Object> razasObj = razaController.getAll();
            return razaController.ConvertList<Raza>(razasObj);
        }

        private List<Provincia> ObtenerProvinciasGallinas()
        {
            ProvinciaController provinciaController = new ProvinciaController();
            List<Object> provinciasObj = provinciaController.getAll();
            return provinciaController.ConvertList<Provincia>(provinciasObj);
        }

        private List<Blog> ObtenerBlogsGallinas()
        {
            BlogController blogController = new BlogController();
            List<Object> blogObj = blogController.getAll();
            return blogController.ConvertList<Blog>(blogObj);
        }

        private Home ObtenerDatos(int loggedid,  string selectRaza, string selectProvincia, string inputPoblacion, string inputPrecio, string inputDate, string selectSexo)
        {
            Home home = new Home();
            if (selectRaza != null || selectProvincia != null || inputPoblacion != null || inputPrecio != null || inputDate != null || selectSexo != null)
            {
                home.Gallinas = this.ObtenerListadoGallinasConFiltro(loggedid, selectRaza, selectProvincia, inputPoblacion, inputPrecio, inputDate, selectSexo);
            }
            else
            {
                home.Gallinas = this.ObtenerListadoGallinas(loggedid);
            }
            home.Razas = this.ObtenerRazasGallinas();
            home.Provincias = this.ObtenerProvinciasGallinas();
            home.Blogs = this.ObtenerBlogsGallinas();
            return home;
        }

        public ActionResult Index(string selectRaza, string selectProvincia, string inputPoblacion, string inputPrecio, string inputDate, string selectSexo)
        {
            this.ActualizarSesion();
            int loggedid = 0;
            if (!String.IsNullOrEmpty(Session["logged"] as String))
            {
                loggedid = Convert.ToInt32(Session["loggedid"]);
            }

            Home home = this.ObtenerDatos(loggedid, selectRaza, selectProvincia, inputPoblacion, inputPrecio, inputDate, selectSexo);
            return View(home);
        }

        private void ActualizarSesion()
        {
            if (String.IsNullOrEmpty(Session["controller"] as String))
            {
                this.HttpContext.Session.Add("controller", "Home");
            }
            else
            {
                this.HttpContext.Session["controller"] = "Home";
            }
            if (String.IsNullOrEmpty(Session["view"] as String))
            {
                this.HttpContext.Session.Add("view", "Index");
            }
            else
            {
                this.HttpContext.Session["view"] = "Index";
            }
        }

        private List<Gallina> ObtenerListadoGallinasConFiltro(int loggedid, string selectRaza, string selectProvincia, string inputPoblacion, string inputPrecio, string inputDate, string selectSexo)
        {
            GallinaController gallinaController = new GallinaController();
            string sql = "SELECT g.*, r.raza, u.nombre nombreUsuario, u.foto fotoUsuario, p.Provincia";
            sql += " FROM gallina g";
            sql += " left join raza r on g.idRaza=r.idRaza";
            sql += " left join usuario u on u.idUsuario = g.idUsuario";
            sql += " left join provincias p on p.idProvincias = u.idProvincias";
            sql += " where g.ventas=0";
            if (!string.IsNullOrEmpty(selectRaza))
            {
                if (selectRaza != "Todas")
                {
                    sql += " and r.raza='" + selectRaza + "'";
                }
            }
            if (!string.IsNullOrEmpty(selectProvincia))
            {
                if (selectProvincia != "Todas")
                {
                    sql += " and p.Provincia='" + selectProvincia + "'";
                } 
            }
            //if (!string.IsNullOrEmpty(inputPoblacion))
            //{
            //    sql += " and r.raza='" + inputPoblacion + "'";
            //}
            if (!string.IsNullOrEmpty(inputPrecio))
            {
                sql += " and g.precio<='" + inputPrecio + "'";
            }
            if (!string.IsNullOrEmpty(inputDate))
            {
                sql += " and g.fechaAlta='" + inputDate + "'";
            }
            if (!string.IsNullOrEmpty(selectSexo))
            {
                if (selectSexo != "Todos")
                {
                    sql += " and g.sexo='" + selectSexo + "'";
                }
            }
            List<Object> gallinasObj = gallinaController.getAllGallinaHome(sql);

            return gallinaController.ConvertList<Gallina>(gallinasObj);
        }

        public ActionResult Filtro(string selectRaza, string selectProvincia, string inputPoblacion, string inputPrecio, string inputDate, string selectSexo)
        {
            return RedirectToAction("Index", "Home", new { selectRaza, selectProvincia, inputPoblacion, inputPrecio, inputDate, selectSexo });
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();

           
        }

    }
}

Proyecto_Final/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Proyecto_Final/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Proyecto_Final/Views/Home/Index.cshtml
@model Proyecto_Final.Models.Home
@{
    if (String.IsNullOrEmpty(Session["logged"] as String))
    {
        ViewBag.UserIsLogged = false;
        ViewBag.UserId = "";
    }
    else
    {
        ViewBag.UserIsLogged = true;
        ViewBag.UserId = Session["loggedid"] as String;
    }
}

<div class="section-aj">
    <div class="container">
        <div class="row">
            <!--filtro-->
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 izquierda-aj">
                <form role="form" controller="Home" action="/Home/Filtro">
                    <div class="form-group">
                        <label for="selectRaza">Raza</label>
                        <select id="selectRaza" name="selectRaza" class="form-control">
                            <option value="" disabled selected>Selecciona una raza</option>
                            <option>Todas</option>
                            @foreach (var raza in Model.Razas)
                            {
                                <option>@raza.Nombre</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="selectProvincia">Província</label>
                        <select name="selectProvincia" id="selectProvincia" class="form-control">
                            <option value="" disabled selected>Selecciona una província</option>
                            <option>Todas</option>
                            @foreach (var provincia in Model.Provincias)
                            {
                                <option>@provincia.Nombre</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="inputPrecio">Precio</label>
                        <input id="inputPrecio" name="inputPrecio" type="text" class="form-control" placeholder="Precio" />
                    </div>
                    <div class="form-group">
                        <label for="selectSexo">Sexo</label>
                        <select id="selectSexo" name="selectSexo" class="form-control">
                            <option value="" disabled selected>Todos</option>
                            <option>Macho</option>
                            <option>Hembra</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success">Filtrar</button>
                </form>
            </div>
            <!--fin filtro-->
            <!--listado gallinas-->
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 ">
                <div class="row">
                    @foreach (var gallina in Model.Gallinas)
                    {
                        

                        
                            <div class="col-sm-4 blog-card-aj">
                                
                                <div class="card-aj">
                                    <div class="single-post post-style-1">
                                        <a class="sinSubrallado-aj" href=@Url.Action("Detail", "Gallina", new { id = gallina.IdGallina })>
                                            <div class="blog-image-aj"><img class="image-aj img-responsive" src="@gallina.Foto" alt="Blog Image"></div>
                                        </a>
                                        
                                            @if (ViewBag.UserIsLogged) 
                                            {
                                                <a href=@Url.Action("MarcarFavorito", "Favorito", new { idUsuario = ViewBag.UserId, idGallina = gallina.IdGallina, callingView=Path.GetFileNameWithoutExtension(Server.MapPath(VirtualPath)) }) onclick="changeImage();">
                                                    <img id="imgFavoritos" class="favorito-aj" src="@gallina.Favorito" />
                                                </a>
                                            }
                                        
                                        
                                            <a class="avatar-aj" href=@Url.Action("Perfil", "Usuario", new { idUsuario = gallina.IdUsuario })>
                                                <img src="@gallina.FotoUsuario" alt="Profile Image">
                                            </a>
                                        
                                        <a class="sinSubrallado-aj" href=@Url.Action("Detail", "Gallina", new { id = gallina.IdGallina })>
                                            <div class="blog-info">
                                                <div class="precio-aj">@gallina.Precio€</div>
                                                <div class="nombreRaza-aj">
                                                    @gallina.Raza
                                                </div>
                                                <div class="nombreLocalidad-aj">@gallina.Localidad</div>

                                                <div class="post-footer-aj">
                                                    <div class="horizontal-aj">
                                                        @for (int i = 0; i < gallina.HuevosGallina; ++i)
                                                        {
                                                            <img style="height:25px;width:20px;"src="~/images/huevo1.png" />
                                                        }
                                                    </div>

                                                    <div class="horizontal-aj">
														<i class="fas fa-eye"></i>
                                                        <p class="icon-aj">@gallina.Views</p>
                                                    </div>
                                                </div>

                                            </div>
                                        </a>
                                    </div>
                                </div>
                                    
                            </div>
                        
                    }

                </div>
            </div>

            <!--blog-->
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12  derecha-aj">
				<div class="blog-aj">
					<p class="textoBlog-aj">MI PRIMERA GALLINA</p>
					<a href="@Url.Action("Index", "Blog")" class="imgBlog-aj"><img class="img-responsive foto-blog-Dm" src="~/images/gallinafeliz.jpg" /></a>
					
				</div>
                @foreach (var blog in Model.Blogs)
                {
                    <a href=@Url.Action("Blog", "Blog", new { idBlog = blog.IdBlog }) class="itemBlog-aj">
                        <div class="itemBlog-aj">
                            @blog.Titulo
                        </div>
                    </a>
                }
                <a href="@Url.Action("Index", "Blog")" class="enlaceBlogsHome-aj">Ver todos</a>
            </div>
            <!--fin blog-->
        </div>
    </div>
</div>