Proyecto_Final/Models/Favorito.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyecto_Final.Models
{
    public class Favorito
    {
        public int IdFavorito { get; set; }
        public int IdGallina { get; set; }
        public int IdUsuario { get; set; }
    }
}

Proyecto_Final/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Proyecto_Final.Models
{
    public class Usuario
    {
        public int IdUsuario { get; set; } // no necesaria
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Apellidos { get; set; }
        [Required]
        public DateTime Edad { get; set; }
        
        public DateTime FechadeAlta { get; set; } // no necesaria
        [Required]
        public int IdProvincias { get; set; }
        public string Provincia { get; set; }
        public double Puntuacion { get; set; }
        public List<ComentarioVenta> Comentarios { get; set; }
        public List<Gallina> Gallinas { get; set; }
        public List<ComentarioVentaPendiente> ComentariosPendientesVentas { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "{0} ha de tenir entre {2} i {1} caracters.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Compare("Password")]
        [Display(Name = "Confirmació de password")]
        public string ConfirmPassword { get; set; }


        public string Foto { get; set; }
    }

}

Proyecto_Final/Controllers/FavoritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_Final.Models;
using MySql.Data.MySqlClient;

namespace Proyecto_Final.Controllers
{
    public class FavoritoController : BaseController
    {
        // GET: Favorito
        public ActionResult Index()
        {
            return View();
        }

        public FavoritoController() : base()
        {
            this._model = new Favorito();
            this._table = "favorito";
        }

        public bool ConsultarFavorito(int idUsuario, int idGallina)
        {
            if (_conn.State == System.Data.ConnectionState.Closed)
            {
                _conn.Open();
            }
            try
            {
                string sql = "SELECT *";
                sql += " FROM favorito f";
                sql += " WHERE f.idUsuario = " + idUsuario + " and f.idGallina = " + idGallina + ";";
                MySqlCommand cmd = new MySqlCommand(sql, _conn);
                MySqlDataReader rdr = cmd.ExecuteReader();
                bool resultado = false;
                if (rdr.Read())
                {
                    resultado = true;
                }
                rdr.Close();
                _conn.Close();
                return resultado;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                _conn.Close();
                return false;
            }
        }

        public ActionResult MarcarFavorito(int idUsuario, int idGallina, string callingView)
        {
            bool favorito = this.ConsultarFavorito(idUsuario, idGallina);
            if (!favorito)
            {
                this.Insertar(idUsuario, idGallina);
            }
            else
            {
                this.Eliminar(idUsuario, idGallina);
            }
            if (callingView == "Favoritos")
            {
                return RedirectToAction("Favoritos", "Usuario", new { idUsuario });
            }
            else if (callingView == "Index")
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        private void Eliminar(int idUsuario, int idGallina)
        {
            if (_conn.State == System.Data.ConnectionState.Closed)
            {
                _conn.Open();
            }
            try
            {
                string sql = "DELETE FROM favorito";
                sql += " WHERE idGallina=" + idGallina + " and idUsuario=" + idUsuario + ";";
                MySqlCommand cmd = new MySqlCommand(sql, _conn);
                MySqlDataReader rdr = cmd.ExecuteReader();
                rdr.Close();
                _conn.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                _conn.Close();
            }
        }

        private void Insertar(int idUsuario, int idGallina)
        {
            if (_conn.State == System.Data.ConnectionState.Closed)
            {
                _conn.Open();
            }
            try
            {
                string sql = "INSERT INTO favorito (idGallina, idUsuario)";
                sql += " VALUES (" + idGallina + ", " + idUsuario + ");";
                MySqlCommand cmd = new MySqlCommand(sql, _conn);
                MySqlDataReader rdr = cmd.ExecuteReader();
                rdr.Close();
                _conn.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                _conn.Close();
            }
        }

        public override Object ToModel(MySqlDataReader rdr)
        {
            Favorito Favorito = new Favorito();
            Favorito.IdFavorito = Convert.ToInt32(rdr["idFavorito"]);
            Favorito.IdGallina = Convert.ToInt32(rdr["idGallina"]);         
            Favorito.IdUsuario = Convert.ToInt32(rdr["idUsuario"]);          
            return Favorito; 
        }
    }
}

Proyecto_Final/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_Final.Models;
using MySql;
using MySql.Data.MySqlClient;

namespace Proyecto_Final.Controllers
{
    public class UsuarioController : BaseController
    {
        ComentarioVentaController comentarioVentaController;
        GallinaController gallinaController;

        public UsuarioController() : base()
        {
           this._model = new Usuario();
           this._table = "usuario";
           this.comentarioVentaController = new ComentarioVentaController();
           this.gallinaController = new GallinaController();
        }

        // GET: Usuario
        public ActionResult Index()
        {
            // convertim llista d'objectes en llista d'usuaris
            List<Usuario> Model = this.getAll().Cast<Usuario>().ToList();
            return View(Model);
        }

        private void ActualizarSesion()
        {
            if (String.IsNullOrEmpty(Session["controller"] as String))
            {
                this.HttpContext.Session.Add("controller", "Home");
            }
            else
            {
                this.HttpContext.Session["controller"] = "Home";
            }
            if (String.IsNullOrEmpty(Session["view"] as String))
            {
                this.HttpContext.Session.Add("view", "Index");
            }
            else
            {
                this.HttpContext.Session["view"] = "Index";
            }
        }

        public ActionResult Perfil(int idUsuario)
        {

            int loggedid = 0;
            if (!String.IsNullOrEmpty(Session["logged"] as String))
            {
                loggedid = Convert.ToInt32(Session["loggedid"]);
            }
            Usuario usuario = this.ObtenerDatosUsuario(idUsuario, loggedid);
            
            return View(usuario);
        }

        private Usuario ObtenerDatosUsuario(int idUsuario, int loggedid)
        {
            string sql = "SELECT u.*, p.Provincia";
            sql += " FROM usuario u";
            sql += " left join provincias p on p.idProvincias = u.idProvincias";
            sql += " where u.idUsuario='" + idUsuario + "';"; 
            Usuario usuario = (Usuario) this.getId("idUsuario", idUsuario, sql);
            usuario.Gallinas = this.ObtenerListadoGallinas(loggedid, idUsuario);
            usuario.Comentarios = this.ObtenerListadoComentarios(idUsuario);
            usuario.Puntuacion = this.ObtenerPuntuacion();
            usuario.ComentariosPendientesVentas = this.ComprobarVentas(loggedid);
            return usuario;
        }

        private List<ComentarioVentaPendiente> ComprobarVentas(int loggedid)
        {
            VentasController ventasController = new VentasController();
            return ventasController.ComprobarVentasUsuario(loggedid);
        }


        public ActionResult Logout(string actionName, string controllerName, int idUsuarioPerfil, int idGallinaDetail, int idBlog)
        {
            this.HttpContext.Session.Remove("loggedid");
            this.HttpContext.Session.Remove("logged");
            this.HttpContext.Session.Remove("loggedfoto");
            if (actionName == "Index" && controllerName == "Home")
            {
                return RedirectToAction("Index", "Home");
            }
            else if (actionName == "Perfil")
            {
                return RedirectToAction("Perfil", "Usuario", new { idUsuario = idUsuarioPerfil });
            }
            else if (actionName == "Detail")
            {
                return RedirectToAction("Detail", "Gallina", new { id = idGallinaDetail });
            }
            else if (actionName == "Blog" && controllerName == "Blog")
            {
                return RedirectToAction("Blog", "Blog", new { idBlog });
            }
            else if (controllerName == "Blog")
            {
                return RedirectToAction("Index", "Blog");
            }
            return RedirectToAction("Index", "Home");
        }


        private List<Gallina> ObtenerListadoGallinas(int loggedid, int idUsuario)
        {
            return this.gallinaController.ObtenerGallinas(loggedid, idUsuario);
        }

        private double ObtenerPuntuacion()
        {
            return this.comentarioVentaController.Puntuacion;
        }

        private List<ComentarioVenta> ObtenerListadoComentarios(int idUsuario)
        {
            List<Object> comentariosObj = this.comentarioVentaController.ObtenerComentarios(idUsuario);
            return this.comentarioVentaController.ConvertList<ComentarioVenta>(comentariosObj);
        }

        public ActionResult Favoritos(int idUsuario)
        {
            List<Gallina> gallinas = this.ObtenerListadoGallinasFavoritas(idUsuario);
            return View(gallinas);
        }

        private List<Gallina> ObtenerListadoGallinasFavoritas(int idUsuario)
        {
            return this.ConvertList<Gallina>(this.gallinaController.ObtenerGallinasFavoritas(idUsuario));
        }
        public void SelectLocalidad()
        {
            ProvinciaController craza = new ProvinciaController();
            List<Provincia> ll = craza.GetProvincias();
            List<SelectListItem> sl = new List<SelectListItem>();
            foreach (Provincia r in ll)
            {
                SelectListItem item = new SelectListItem();
                item.Value = r.IdProvincias.ToString();
                item.Text = r.Nombre;
                sl.Add(item);
            }

            ViewBag.Localidad = sl;
        }

        //GET
        public ActionResult Registro()
        {
            this.SelectLocalidad();
            return View();
        }
        public string GuardarFoto(HttpPostedFileBase file, string profileFoto)
        {
            Random rmd = new Random();

            int x = rmd.Next(0, 3000);

            string db_path = "null";

            if (file != null && file.FileName.Length > 0)//si no hay audio FileName esta vacio
            {
                //ojo con posibles espacios en blanco ...
                string pic = "Foto" + x.ToString() + profileFoto + System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/Images/PerfilesUsuarios"), pic);
                db_path = "/Images/PerfilesUsuarios/" + pic;
                // file is uploaded
                file.SaveAs(path);
            }
            return db_path;
        }//OK
        // POST: Registro
        [HttpPost]
        public ActionResult Registro(FormCollection collection)
        {

            // TODO: Add insert logic here
            openConn(); //método propio que abre conexión si está cerrada
                        //obtenemos email y pass, codificamos pass
            HttpPostedFileBase file = Request.Files[0];
           
            string Nombre = collection["Nombre"] as String;
            string Apellidos = collection["Apellidos"] as String;
            string Edad = collection["Edad"] as String;
            string IdProvincia = collection["IdProvincias"] as String;
            string Email =  collection["Email"] as String;
            string Password = collection["Password"] as String;
            string ConfirmPassword = collection["ConfirmPassword"] as String;
            string Foto = this.GuardarFoto(file,Nombre);
            if (emailExisteix(Email))
            {
                ViewBag.ErrorMensaje = "Ya existe este correo";
            }
            Password = Codifica.ConverteixPassword(Password);
            
            try
            {
                string sql = "INSERT INTO usuario (nombre, apellidos, edad, idProvincias,  correo, password, foto) VALUES (@Nombre, @Apellidos, @Edad, @IdProvincia, @Email, @Password,@Foto);";
                MySqlCommand cmd = new MySqlCommand();
                openConn();
                cmd.CommandText = sql;
                cmd.Connection = _conn;
                cmd.Parameters.AddWithValue("@Nombre", Nombre);
                cmd.Parameters.AddWithValue("@Apellidos", Apellidos);
                cmd.Parameters.AddWithValue("@Edad", Edad);
                cmd.Parameters.AddWithValue("@idProvincia", IdProvincia);
                cmd.Parameters.AddWithValue("@Email", Email);
                cmd.Parameters.AddWithValue("@Password", Password);
                cmd.Parameters.AddWithValue("@Foto", Foto);
                cmd.Prepare();
                cmd.ExecuteNonQuery();

                //select per trobar darrer id
                sql = "SELECT LAST_INSERT_ID() AS ultim;";
                MySqlCommand cmd2 = new MySqlCommand(sql, _conn);
                MySqlDataReader rdr = cmd2.ExecuteReader();
                if (rdr.Read())
                {
                    string cosa = rdr["ultim"].ToString();
                    int idinsertat = Convert.ToInt32(cosa);
                    //this.HttpContext.Session.Add("logged", nombre + idinsertat);
                    this.HttpContext.Session.Add("loggedid", idinsertat.ToString());
                    this.HttpContext.Session.Add("logged",Nombre);                   
                    this.HttpContext.Session.Add("loggedfoto", Foto);

                }



                closeConn(); //método propio que cierra conexión si está abierta

   

                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                string s = e.Message;
                ViewBag.MsgError = "S'ha produit un error...";
                return View();
            }
            
        }

        public override Object ToModel(MySqlDataReader rdr)
        {
            Usuario usuario = new Usuario();
            usuario.IdUsuario = Convert.ToInt32(rdr["idUsuario"]);
            usuario.Nombre = rdr["nombre"].ToString();
            usuario.Apellidos = rdr["apellidos"].ToString();
            usuario.Edad = Convert.ToDateTime(rdr["edad"]);

Proyecto_Final/Views/Usuario/Create.cshtml
@model Proyecto_Final.Models.Usuario

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechadeAlta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechadeAlta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechadeAlta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdProvincias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdProvincias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdProvincias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    }

Proyecto_Final/Views/Usuario/Favoritos.cshtml
@model IEnumerable<Proyecto_Final.Models.Gallina>
@{
    if (String.IsNullOrEmpty(Session["logged"] as String))
    {
        ViewBag.UserIsLogged = false;
        ViewBag.UserId = "";
    }
    else
    {
        ViewBag.UserIsLogged = true;
        ViewBag.UserId = Session["loggedid"] as String;
    }
}


<div class="row">
    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1 "></div>
    <div class="col-lg-11 col-md-11 col-sm-11 col-xs-11">
        <div class="title-aj">Mis gallinas favoritas</div>
    </div>
</div>

<div class="row">
    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1 "></div>
    <div class="col-lg-11 col-md-11 col-sm-11 col-xs-11">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <a class="enlace-aj" href=@Url.Action("Perfil", "Usuario", new { idUsuario = @ViewBag.UserId })>Volver</a>
            </div>
        </div>
        <div class="row">
            <div class="section-aj">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @foreach (var gallina in Model)
                    {
                        <div class="col-sm-3 blog-card-aj">
                            <div class="card-aj">

                                <div class="single-post post-style-1">
                                    <a class="sinSubrallado-aj" href=@Url.Action("Detail", "Gallina", new { id = gallina.IdGallina })>
                                        <div class="blog-image-aj">
                                            <img class="image-aj img-responsive" src="@gallina.Foto" alt="Blog Image">
                                        </div>
                                    </a>
                                    <div>
                                        <a href=@Url.Action("MarcarFavorito", "Favorito", new { idUsuario = ViewBag.UserId, idGallina = gallina.IdGallina, callingView=Path.GetFileNameWithoutExtension(Server.MapPath(VirtualPath)) })>
                                            <img class="favorito-aj" src="~/images/icons8-heart-red-32.png" />
                                        </a>
                                    </div>
                                    <div>
                                        <a class="avatar-aj" href="#"><img src="@gallina.FotoUsuario" alt="Profile Image"></a>
                                    </div>
                                    <a class="sinSubrallado-aj" href=@Url.Action("Detail", "Gallina", new { id = gallina.IdGallina })>
                                        <div class="blog-info">
                                            <div class="precio-aj"><b>@gallina.Precio€</b></div>
                                            <div class="nombreRaza-aj">
                                                <b>@gallina.Raza</b>
                                            </div>
                                            <div class="nombreLocalidad-aj">@gallina.Localidad</div>

                                            <div class="post-footer-aj">
                                                <div class="horizontal-aj">
                                                    @for (int i = 0; i < gallina.HuevosGallina; ++i)
                                                    {
                                                        <img style="height:30px;width:25px;" src="~/images/huevo1.png" />
                                                    }
                                                </div>

                                                <div class="horizontal-aj">
                                                    <img src="~/images/icons8-eye-16.png" />
                                                    <p class="icon-aj">@gallina.Views</p>
                                                </div>
                                            </div>

                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    }
                </div>




            </div>
        </div>

Proyecto_Final/Views/Usuario/Index.cshtml
@model IEnumerable<Proyecto_Final.Models.Usuario>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdUsuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellidos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechadeAlta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdProvincias)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdUsuario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellidos)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Foto)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {  id=item.IdUsuario }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>